# Generated by Django 3.1.7 on 2021-03-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_date',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='삭제일자'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일자'),
        ),
    ]
