# Generated by Django 3.1.7 on 2021-03-30 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('field', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=140)),
                ('experience_level', models.CharField(choices=[('신입', 'Junior'), ('경력', 'Senior'), ('무관', 'Any')], default='무관', max_length=5)),
                ('type', models.CharField(choices=[('인턴', 'Intern'), ('파트타임', 'Part Time'), ('풀타임', 'Full Time'), ('프리랜서', 'Freelancer')], max_length=5)),
                ('salary_min', models.PositiveSmallIntegerField()),
                ('salary_max', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('채용담당자', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(through='company.Employment', to=settings.AUTH_USER_MODEL),
        ),
    ]
