# Generated by Django 3.1.7 on 2021-03-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_exps', related_query_name='work_exp', to='user.userprofile'),
        ),
    ]
