# Generated by Django 3.1.7 on 2021-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210329_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제일자'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제일자'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제일자'),
        ),
    ]
