# Generated by Django 3.1.7 on 2021-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210329_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
