# Generated by Django 3.1.7 on 2021-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210329_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
