# Generated by Django 3.1.7 on 2021-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210329_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='field',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
